name: reviewdog
on:
  pull_request:

jobs:
  golangci-lint:
    name: runner / golangci-lint
    permissions:
      checks: write
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - uses: reviewdog/action-golangci-lint@v2
        with:
          go_version: "1.21"
          golangci_lint_version: "v1.53.3" # use latest version by default
          golangci_lint_flags: "-v --timeout 10m"
          fail_on_error: true

  staticcheck:
    name: runner / staticcheck
    permissions:
      checks: write
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v3
        with:
          go-version: "1.21"

      - uses: reviewdog/action-staticcheck@v1
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          filter_mode: nofilter
          fail_on_error: true
